// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-x5zVcJFUz6d7Rx5b5lUFmkIZl9UsWaU',
    appId: '1:551172864201:web:02768c95c77e1228293518',
    messagingSenderId: '551172864201',
    projectId: 'adityaraorane-c8a1f',
    authDomain: 'adityaraorane-c8a1f.firebaseapp.com',
    storageBucket: 'adityaraorane-c8a1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG_BcEeXTLGVMsXb_XhwvMDmISMLab51A',
    appId: '1:551172864201:android:74ce53daaffbb9fd293518',
    messagingSenderId: '551172864201',
    projectId: 'adityaraorane-c8a1f',
    storageBucket: 'adityaraorane-c8a1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV9RTcQiuaWyl2jKd9qb5d4s4BPVu8ui0',
    appId: '1:551172864201:ios:60326efdc1bf8873293518',
    messagingSenderId: '551172864201',
    projectId: 'adityaraorane-c8a1f',
    storageBucket: 'adityaraorane-c8a1f.firebasestorage.app',
    iosBundleId: 'com.example.riderio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV9RTcQiuaWyl2jKd9qb5d4s4BPVu8ui0',
    appId: '1:551172864201:ios:60326efdc1bf8873293518',
    messagingSenderId: '551172864201',
    projectId: 'adityaraorane-c8a1f',
    storageBucket: 'adityaraorane-c8a1f.firebasestorage.app',
    iosBundleId: 'com.example.riderio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-x5zVcJFUz6d7Rx5b5lUFmkIZl9UsWaU',
    appId: '1:551172864201:web:f2d0dc78e666ab4c293518',
    messagingSenderId: '551172864201',
    projectId: 'adityaraorane-c8a1f',
    authDomain: 'adityaraorane-c8a1f.firebaseapp.com',
    storageBucket: 'adityaraorane-c8a1f.firebasestorage.app',
  );
}
